export type Place = {
  /** URL-safe id — photo path is /images/places/{slug}.jpg */
  slug: string;
  name: string;
  /** [longitude, latitude] */
  coords: [number, number];
  /** Optional era label shown under city name, e.g. "2018–2022" */
  dateLabel?: string;
  note: string;
  /** Override default /images/places/{slug}.jpg */
  photo?: string;
  country: string;
  featured?: boolean;
};

export const GEO_URL = "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json";

export function placePhotoSrc(place: Place) {
  return place.photo ?? `/images/places/${place.slug}.jpg`;
}

/** Primary cities for auto-play — order controls carousel sequence */
export const places: Place[] = [

  {
    slug: "los-angeles",
    name: "Los Angeles",
    coords: [-118.24, 34.05],
    dateLabel: "2019",
    note: "First stretch of life in the US — sun, sprawl, and a different rhythm.",
    photo: "/images/places/los-angeles.jpg",
    country: "United States of America",
    featured: true,
  },
  {
    slug: "san-diego",
    name: "San Diego",
    coords: [-117.16, 32.72],
    dateLabel: "2024",
    note: "Tacos El Gordo through the window — adobada, neon, and Halloween stickers.",
    photo: "/images/places/san-diego.jpg",
    country: "United States of America",
  },
  {
    slug: "beijing",
    name: "Beijing",
    coords: [116.4, 39.9],
    note: "School, early work, and learning how people read the world.",
    country: "China",
    featured: true,
  },
  {
    slug: "sanya",
    name: "Sanya",
    coords: [109.51, 18.25],
    dateLabel: "2022",
    note: "Turquoise water, fishing boats, and mountains behind the skyline.",
    photo: "/images/places/sanya.jpg",
    country: "China",
  },
  {
    slug: "jinan",
    name: "Jinan",
    coords: [117.0, 36.65],
    dateLabel: "2023",
    note: "Snow on the hedges, cathedral stone, and a lit Christmas tree.",
    photo: "/images/places/jinan.jpg",
    country: "China",
  },
  {
    slug: "suzhou",
    name: "Suzhou",
    coords: [120.62, 31.32],
    dateLabel: "2023",
    note: "Gate of the Orient at night — blue light on the lake.",
    photo: "/images/places/suzhou.jpg",
    country: "China",
  },
  {
    slug: "wuxi",
    name: "Wuxi",
    coords: [120.31, 31.57],
    dateLabel: "2024",
    note: "Lake sunset through the trees — chairs out, light on the water.",
    photo: "/images/places/wuxi.jpg",
    country: "China",
  },
  {
    slug: "dali",
    name: "Dali",
    coords: [100.23, 25.59],
    dateLabel: "2024",
    note: "A bag full of roses — pink, peach, and yellow on the street.",
    photo: "/images/places/dali.jpg",
    country: "China",
  },
  {
    slug: "shangri-la",
    name: "Shangri-La",
    coords: [99.71, 27.83],
    dateLabel: "2024",
    note: "Songzanlin on the hill — gold roofs above the lake.",
    photo: "/images/places/shangri-la.jpg",
    country: "China",
  },
  {
    slug: "meili-snow-mountain",
    name: "Meili Snow Mountain",
    coords: [98.91, 28.39],
    dateLabel: "2024",
    note: "Prayer flags in the branches — snow peaks behind the clouds.",
    photo: "/images/places/meili-snow-mountain.jpg",
    country: "China",
  },
  {
    slug: "xishuangbanna",
    name: "Xishuangbanna",
    coords: [100.8, 22.01],
    dateLabel: "2024",
    note: "Palm trees on the street — scooters, shops, and pink evening sky.",
    photo: "/images/places/xishuangbanna.jpg",
    country: "China",
  },
  {
    slug: "wenquan",
    name: "Wenquan",
    coords: [81.03, 44.97],
    dateLabel: "2025",
    note: "Horses in the snow — golden light on the peaks and bare poplars.",
    photo: "/images/places/wenquan.jpg",
    country: "China",
  },
  {
    slug: "jingmai-mountain",
    name: "Jingmai Mountain",
    coords: [100.01, 22.67],
    dateLabel: "2025",
    note: "Village rooftops in the mist — tea hills and morning light on the horizon.",
    photo: "/images/places/jingmai-mountain.jpg",
    country: "China",
  },
  {
    slug: "baihaba",
    name: "Baihaba",
    coords: [86.78, 48.7],
    dateLabel: "2023",
    note: "Log cabins, snow on the peaks, and cattle at the edge of the village.",
    photo: "/images/places/baihaba.jpg",
    country: "China",
  },
  {
    slug: "kanas",
    name: "Kanas",
    coords: [87.05, 48.72],
    dateLabel: "2023",
    note: "Turquoise river bend, golden larches, and snow on the far ridges.",
    photo: "/images/places/kanas.jpg",
    country: "China",
  },
  {
    slug: "sayram-lake",
    name: "Sayram Lake",
    coords: [81.13, 44.6],
    dateLabel: "2023",
    note: "Deep blue water, snow-streaked peaks, and clouds rolling over the pass.",
    photo: "/images/places/sayram-lake.jpg",
    country: "China",
  },
  {
    slug: "chicago",
    name: "Chicago",
    coords: [-87.63, 41.88],
    dateLabel: "2019",
    note: "Home base now. Lake Michigan, Northwestern, building in public.",
    photo: "/images/places/chicago.jpg",
    country: "United States of America",
    featured: true,
  },
  {
    slug: "new-york",
    name: "New York",
    coords: [-73.98, 40.75],
    dateLabel: "2019",
    note: "Grand Central light — marble arches and a first taste of the city.",
    photo: "/images/places/new-york.jpg",
    country: "United States of America",
  },
  {
    slug: "san-francisco",
    name: "San Francisco",
    coords: [-122.48, 37.82],
    dateLabel: "2024",
    note: "Golden Gate at dusk — orange sky, rocks, and people watching the view.",
    photo: "/images/places/san-francisco.jpg",
    country: "United States of America",
  },
  {
    slug: "seattle",
    name: "Seattle",
    coords: [-122.33, 47.61],
    dateLabel: "2024",
    note: "Mount Rainier from the trail — snow peak, meadow, and a log bridge.",
    photo: "/images/places/seattle.jpg",
    country: "United States of America",
  },
  {
    slug: "seville",
    name: "Seville",
    coords: [-5.98, 37.39],
    dateLabel: "2025",
    note: "Plaza de España — tiled bridges, red brick arches, and boats on the canal.",
    photo: "/images/places/seville.jpg",
    country: "Spain",
  },
  {
    slug: "barcelona",
    name: "Barcelona",
    coords: [2.17, 41.39],
    dateLabel: "2025",
    note: "Sagrada Família at golden hour — city, sea, and pine branches.",
    photo: "/images/places/barcelona.jpg",
    country: "Spain",
  },
  {
    slug: "granada",
    name: "Granada",
    coords: [-3.6, 37.18],
    dateLabel: "2025",
    note: "Court of the Lions at the Alhambra — marble columns and carved arches.",
    photo: "/images/places/granada.jpg",
    country: "Spain",
  },
  {
    slug: "collioure",
    name: "Collioure",
    coords: [3.08, 42.53],
    dateLabel: "2025",
    note: "Peach and yellow walls — Catalan flag, iron balconies, and sun on the alley.",
    photo: "/images/places/collioure.jpg",
    country: "France",
  },
  {
    slug: "perugia",
    name: "Perugia",
    coords: [12.39, 43.11],
    dateLabel: "2023",
    note: "Terracotta roofs, green hills, and a view from the old town wall.",
    photo: "/images/places/perugia.jpg",
    country: "Italy",
  },
  {
    slug: "florence",
    name: "Florence",
    coords: [11.25, 43.77],
    dateLabel: "2023",
    note: "Primavera at the Uffizi — myth, spring, and a room full of strangers.",
    photo: "/images/places/florence.jpg",
    country: "Italy",
  },
  {
    slug: "rome",
    name: "Rome",
    coords: [12.49, 41.9],
    dateLabel: "2023",
    note: "Trevi at night — stone lit up, water still, phone in hand.",
    photo: "/images/places/rome.jpg",
    country: "Italy",
  },
  {
    slug: "venice",
    name: "Venice",
    coords: [12.34, 45.44],
    dateLabel: "2023",
    note: "Gondola at dusk — warm balcony light on the canal.",
    photo: "/images/places/venice.jpg",
    country: "Italy",
  },
  {
    slug: "hobart",
    name: "Hobart",
    coords: [147.33, -42.88],
    dateLabel: "2023",
    note: "Hillside houses across the water — boats, pier, and open sky.",
    photo: "/images/places/hobart.jpg",
    country: "Australia",
  },
  {
    slug: "launceston",
    name: "Launceston",
    coords: [147.14, -41.43],
    dateLabel: "2024",
    note: "Shell station at dusk — pink clouds over an ordinary corner of town.",
    photo: "/images/places/launceston.jpg",
    country: "Australia",
  },
  {
    slug: "melbourne",
    name: "Melbourne",
    coords: [144.96, -37.81],
    dateLabel: "2024",
    note: "Red walls at the NGV — gold frames floor to ceiling.",
    photo: "/images/places/melbourne.jpg",
    country: "Australia",
  },
  {
    slug: "kota-kinabalu",
    name: "Kota Kinabalu",
    coords: [116.07, 5.98],
    dateLabel: "2024",
    note: "Sunset over the water — orange sky, dark horizon, light on the waves.",
    photo: "/images/places/kota-kinabalu.jpg",
    country: "Malaysia",
  },
  {
    slug: "semporna",
    name: "Semporna",
    coords: [118.61, 4.48],
    dateLabel: "2024",
    note: "Turquoise shallows — a white boat cutting across the blue.",
    photo: "/images/places/semporna.jpg",
    country: "Malaysia",
  },
  {
    slug: "luang-prabang",
    name: "Luang Prabang",
    coords: [102.13, 19.89],
    dateLabel: "2025",
    note: "White roofs and the Mekong — town, river, and green hills from above.",
    photo: "/images/places/luang-prabang.jpg",
    country: "Laos",
  },

  {
    slug: "chiang-mai",
    name: "Chiang Mai",
    coords: [100.5, 18.78],
    dateLabel: "2025",
    note: "sunset on the mountain",
    photo: "/images/places/chiang-mai.jpg",
    country: "Thailand",
  },

  {
    slug: "iceland",
    name: "Iceland",
    coords: [-19.02, 64.13],
    dateLabel: "2025",
    note: "iceberg",
    photo: "/images/places/iceland.jpg",
    country: "Iceland",
  },

  {
    slug: "grand-canyon",
    name: "Grand Canyon",
    coords: [-112.14, 36.06],
    dateLabel: "2025",
    note: "squarrel",
    photo: "/images/places/grand-canyon.jpg",
    country: "United States of America",
  },

  {
    slug: "dubai",
    name: "Dubai",
    coords: [55.3, 25.2],
    dateLabel: "2025",
    note: "desert dunes",
    photo: "/images/places/dubai.jpg",
    country: "United Arab Emirates",
  },

  {
    slug: "okinawa",
    name: "Okinawa",
    coords: [127.8, 26.6],
    dateLabel: "2025",
    note: "sunset at American Village",
    photo: "/images/places/okinawa.jpg",
    country: "Japan",
  },
  {
    slug: "arizona",
    name: "Arizona",
    coords: [-111.09, 34.57],
    dateLabel: "2025",
    note: "road trip",
    photo: "/images/places/arizona.jpg",
    country: "United States of America",
  },

  {
    slug: "page",
    name: "Page",
    coords: [-111.5, 36.91],
    dateLabel: "2025",
    note: "road trip",
    photo: "/images/places/page.jpg",
    country: "United States of America",
  },

  {
    slug: "bryce-canyon",
    name: "Bryce Canyon",
    coords: [-112.9, 37.7],
    dateLabel: "2025",
    note: "snow and canyon",
    photo: "/images/places/bryce-canyon.jpg",
    country: "United States of America",
  },

  {
    slug: "las-vegas",
    name: "Las Vegas",
    coords: [-115.14, 36.17],
    dateLabel: "2025",
    note: "city sunsets",
    photo: "/images/places/las-vegas.jpg",
    country: "United States of America",
  },

  {
    slug: "yosemite",
    name: "Yosemite",
    coords: [-119.5, 37.8],
    dateLabel: "2025",
    note: "mountain views",
    photo: "/images/places/yosemite.jpg",
    country: "United States of America",
  },

  {
    slug: "casablanca",
    name: "Casablanca",
    coords: [-11.69, 33.5],
    dateLabel: "2025",
    note: "coastal views",
    photo: "/images/places/casablanca.jpg",
    country: "Morocco",
  },

  {
    slug: "nanchang",
    name: "Nanchang",
    coords: [115.89, 28.67],
    dateLabel: "2021",
    note: "Tengwangg Tower",
    photo: "/images/places/nanchang.jpg",
    country: "China",
  },

  {
    slug: "lushan",
    name: "Lushan",
    coords: [115.98, 29.57],
    dateLabel: "2021",
    note: "Waterfall",
    photo: "/images/places/lushan.jpg",
    country: "China",
  },

  {
    slug: "wuhan",
    name: "Wuhan",
    coords: [114.3, 30.58],
    dateLabel: "2021",
    note: "ferry",
    photo: "/images/places/wuhan.jpg",
    country: "China",
  },

  {
    slug: "changsha",
    name: "Changsha",
    coords: [113.26, 28.19],
    dateLabel: "2021",
    note: "temple",
    photo: "/images/places/changsha.jpg",
    country: "China",
  },

  {
    slug: "guilin",
    name: "Guilin",
    coords: [110.29, 25.28],
    dateLabel: "2021",
    note: "mountain farm",
    photo: "/images/places/guilin.jpg",
    country: "China",
  },

  {
    slug: "leshan",
    name: "Leshan",
    coords: [103.4, 29.9],
    dateLabel: "2021",
    note: "flowers",
    photo: "/images/places/leshan.jpg",
    country: "China",
  },

  {
    slug: "tianjin",
    name: "Tianjin",
    coords: [117.19, 39.12],
    dateLabel: "2019",
    note: "words",
    photo: "/images/places/tianjin.jpg",
    country: "China",
  },

  {
    slug: "shanghai",
    name: "Shanghai",
    coords: [121.47, 31.23],
    dateLabel: "2021",
    note: "tower and street",
    photo: "/images/places/shanghai.jpg",
    country: "China",
  },

  {
    slug: "yangzhou",
    name: "Yangzhou",
    coords: [119.14, 32.4],
    dateLabel: "2017",
    note: "patio",
    photo: "/images/places/yangzhou.jpg",
    country: "China",
  },

  {
    slug: "jiaxing",
    name: "Jiaxing",
    coords: [120.73, 30.75],
    dateLabel: "2025",
    note: "clouds",
    photo: "/images/places/jiaxing.jpg",
    country: "China",
  },

  {
    slug: "beijing",
    name: "Beijing",
    coords: [116.4, 39.9],
    dateLabel: "2023",
    note: "another home",
    photo: "/images/places/beijing.jpg",
    country: "China",
  },

  {
    slug: "hohhot",
    name: "Hohhot",
    coords: [111.66, 40.82],
    dateLabel: "2023",
    note: "another home",
    photo: "/images/places/hohhot.jpg",
    country: "China",
  },

  {
    slug: "dekalb",
    name: "Dekalb",
    coords: [88.79, 34.62],
    dateLabel: "2019",
    note: "/",
    photo: "/images/places/dekalb.jpg",
    country: "United States of America",
  },

  {
    slug: "evanston",
    name: "Evanston",
    coords: [87.66, 42.05],
    dateLabel: "2025",
    note: "another home",
    photo: "/images/places/evanston.jpg",
    country: "United States of America",
  },
];

export const featuredPlaces = places.filter((p) => p.featured);

export const visitedCountries = [...new Set(places.map((p) => p.country))];
